language: rust
sudo: false

addons:
  apt:
    packages:
      - libssl-dev
      - cmake

os:
  - osx
  - linux

rust:
  - stable
  - beta
  - nightly

cache: cargo

script:
  # install srt
  - git clone https://github.com/haivision/srt
  - mkdir srt/build && cd srt/build
  - cmake .. -DCMAKE_INSTALL_PREFIX=~/.local/
  - cmake --build . --target install
  - export PATH=~/.local/bin:$PATH
  - cd ../..
  # build & run tests
  - cargo build --verbose
  - RUST_LOG=srt=info,lossy=info,message_splitting=info RUST_BACKTRACE=full cargo test --verbose

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == stable ] && [ "$TRAVIS_OS_NAME" == linux ]; then
    `RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin` 
    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
