# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

# Pull in cargo templates
resources:
  repositories:
    - repository: rust_pipelines
      type: github
      name: xoac/rust-azure-pipelines
      ref: refs/heads/master
      endpoint: PipelinesTemplates
stages:
- stage: check
  displayName: "Quick checks"
  jobs:
  - template: ci/scenarios/check.yml@rust_pipelines

- stage: test
  displayName: "Multi OS native tests"
  jobs:
  # Latest stable
  - template: ci/jobs/cargo-test.yaml@rust_pipelines
    parameters:
      test-flags:
        nocapture: true
      skip: 
      - stransmit_client
      - stransmit_server
  # Nightly
  - template: ci/jobs/cargo-test.yaml@rust_pipelines
    parameters:
      rust: nightly
      job_name: cargo_test_nightly
      job_displayName: Cargo test (nightly)
      job_continueOnError: true
      test-flags: 
        nocapture: true
      skip: 
      - stransmit_client
      - stransmit_server
