[package]
name = "srt-transport"
version = "0.2.1"
authors = ["Russell Greene <russellgreene8@gmail.com>"]
description = "SRT implementation in Rust"
license = "Apache-2.0"
documentation = "https://docs.rs/srt"
homepage = "https://github.com/russelltg/srt-rs"
repository = "https://github.com/russelltg/srt-rs"

[dependencies]
tokio-io = "0.1"
tokio-udp = "0.1"
futures = "0.1"
bytes = "0.4"
futures-timer = "0.1"
log = { version = "0.4", default-features = false }
rand = "0.5"
clap = { version = "2", default-features = false }
bitflags = "1"
failure = { version = "0.1", default-features = false, features=["std"] }

env_logger = { version = "0.5", default-features = false, optional = true }
url = { version = "1", optional = true }
tokio-codec = { version = "0.1", optional = true }


[lib]
name = "srt"
path = "src/lib.rs"

[[bin]]
name = "stransmit-rs"
path = "src/bin.rs"

[features]
stransmit-rs = ["env_logger", "url", "tokio-codec"]
default = ["stransmit-rs"]