[package]
name = "srt-transport"
version = "0.2.1"
authors = ["Russell Greene <russellgreene8@gmail.com>"]
description = "SRT implementation in Rust"
license = "Apache-2.0"
documentation = "https://docs.rs/srt-rs"
homepage = "https://github.com/russelltg/srt-rs"
repository = "https://github.com/russelltg/srt-rs"
edition = "2018"

[dependencies]
bitflags = "1"
bytes = "0.4"
clap = { version = "2", default-features = false }
env_logger = { version = "0.6", default-features = false, optional = true }
failure = { version = "0.1", default-features = false, features=["std"] }
futures = "0.1"
log = { version = "0.4", default-features = false }
rand = "0.6"
tokio = "0.1"
url = { version = "1", optional = true }
openssl = {path = "../rust-openssl/openssl"}

[dev-dependencies]
binary_macros = "0.6"

[lib]
name = "srt"
path = "src/lib.rs"

[[bin]]
name = "stransmit-rs"
path = "src/bin.rs"

[features]
stransmit-rs = ["env_logger", "url"]
default = ["stransmit-rs"]
