[package]
name = "srt-transport"
version = "0.2.1"
authors = ["Russell Greene <russellgreene8@gmail.com>"]
description = "SRT implementation in Rust"
license = "Apache-2.0"
documentation = "https://docs.rs/srt"
homepage = "https://github.com/russelltg/srt-rs"
repository = "https://github.com/russelltg/srt-rs"

[dependencies]
tokio-core = "^0.1.12"
tokio-io = "^0.1.5"
tokio = "^0.1"
futures = "^0.1.18"
bytes = "^0.4"
byteorder = "^1.2"
futures-timer = "0.1.1"
log = "0.4.1"
env_logger = "^0.5"
rand = "0.4"
url = "1.7.0"
clap = "2.31.2"

[lib]
name = "srt"
path = "src/lib.rs"

[[bin]]
name = "stransmit-rs"
path = "src/bin.rs"

