steps:
  - task: ShellScript@2
    inputs:
      scriptPath: ./ci/codecov.sh
    displayName: 'Run codecov'
    condition: eq(variables['Agent.OS'], 'Linux')
    env:
      - CODECOV_TOKEN: $(codecov_token)
