name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install srt
      run: sudo apt-get install srt-tools
    - name: Build
      run: cargo build --tests --examples --verbose
    - name: Run tests
      run: cargo test --verbose
      
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cargo clippy
      run: cargo clippy --tests --examples --verbose
  
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt -- --check

  coverage:
    # needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust nightly
      run: rustup install nightly
    - name: install srt
      run: sudo apt-get install srt-tools
    - name: Install grcov
      run: cargo install grcov
    - name: Build with profdata
      run: RUSTFLAGS="-Zinstrument-coverage" cargo +nightly build --tests
    - name: Generate reports
      run: RUSTFLAGS="-Zinstrument-coverage" LLVM_PROFILE_FILE="srt.%p.profraw" cargo +nightly test
    - name: Run grcov
      run: grcov . --binary-path ./target/debug/ -t lcov -s . -o lcov.info
    - name: Upload results
      run: bash <(curl -s https://codecov.io/bash) -f lcov.info